# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet credhub-interpolate start yaml
---
platform: linux

inputs:
- name: files
# contains YAML files with extension `.yml`
# each one of these files will have their values interpolated from credhub
# For some example, run: `credhub interpolate --help` (minimum version >= 2.1.0 required)

outputs:
- name: interpolated-files
#contains all the *.yml files from `files/` input but after interpolation

# all params are required to be filled out
params:
  # credentials to talk to credhub server
  CREDHUB_CA_CERT:
  CREDHUB_CLIENT:
  CREDHUB_SECRET:
  CREDHUB_SERVER:

  # prefix flag used by credhub interpolate
  PREFIX:

  # path the contains the files to read from
  # this is a space separated list of directories
  # the paths are all evaluated relative to files/
  INTERPOLATION_PATH: '.'

run:
  path: bash
  args:
  - "-c"
  - |
    cat /var/version && echo ""
    set -euo pipefail

    # NOTE: The credhub cli does not ignore empty/null environment variables.
    # https://github.com/cloudfoundry-incubator/credhub-cli/issues/68
    if [ -z "$CREDHUB_CA_CERT" ]; then
      unset CREDHUB_CA_CERT
    fi

    credhub --version

    if [ -z "$PREFIX" ]; then
      echo "Please specify a PREFIX. It is required."
      exit 1
    fi

    files=$(cd files && find "$INTERPOLATION_PATH" -type f -name '*.yml' -follow)

    for file in $files; do
      echo "interpolating files/$file"
      mkdir -p interpolated-files/"$(dirname "$file")"
      credhub interpolate --prefix "$PREFIX" --file files/"$file" > interpolated-files/"$file"
    done

# code_snippet credhub-interpolate end
