# code_snippet import-installation start yaml
---
platform: linux

inputs:
- name: env # contains the environment information about the OpsMan
- name: installation # contains the installation to be imported

params:
  ENV_FILE: env.yml
  # - Filepath of the environment config YAML
  # - The path is relative to root of the `env` input
  # - The env file _must_ contain the `decryption-passphrase`
  #   while it's optional for other tasks, this one requires it.
  INSTALLATION_FILE: installation.zip
  # - Optional
  # - Filepath of the installation ZIP file
  # - The path is relative to root of the `installation` input

run:
  path: bash
  args:
  - -c
  - |
    p-automator -v
    set -eux
    om --env env/"${ENV_FILE}" import-installation \
       --installation installation/"${INSTALLATION_FILE}"
# code_snippet import-installation end