# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet test-interpolate start yaml
---
platform: linux

inputs:
- name: config # contains the base configuration file
- name: vars # variable files to be made available
  optional: true

params:
  VARS_FILES:
  # - Optional
  # - Filepath to the Ops Manager vars yaml file
  # - The path is relative to root of the task build,
  #   so `vars` and `secrets` can be used.
  CONFIG_FILE: base.yml

run:
  path: bash
  args:
  - "-c"
  - |
    p-automator -v
    set -eux

    vars_files_args=("")
    for vf in ${VARS_FILES}
    do
      vars_files_args+=("--vars-file ${vf}")
    done

    # ${vars_files_args[@] needs to be globbed in order to pass through properly
    # shellcheck disable=SC2068
    om interpolate --config "config/$CONFIG_FILE" ${vars_files_args[@]}
# code_snippet test-interpolate end
